# Site settings
title: SIDL
description: A Real-World Dataset for Restoring Smartphone Images with Dirty Lenses
baseurl: ""  # organization.github.io를 사용할 경우
url: "https://sidl-benchmark.github.io"  # 만든 organization 이름으로 수정

# Build settings
markdown: kramdown
permalink: /:title/

# Author Settings
author:
  name: Sooyoung Choi, Sungyong Park, Heewon Kim
  affiliation: Soongsil University
  email: hwkim@ssu.ac.kr

# Project Settings
project:
  paper_url: https://arxiv.org/abs/your-paper
  code_url: https://github.com/sidl-dataset/SIDL
  dataset_url: your-dataset-url

# Social Links
social:
  github: https://github.com/sidl-dataset

# Analytics
google_analytics: # your google analytics id

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
